# Source from https://www.masterzendframework.com/docker-development-environment/
---
version: '2'

volumes:
  gocache:
  database_data:
    driver: local

services:
  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php
  php:
    build: ./docker/php/
    expose:
      - 9000
    volumes:
      - ./html:/var/www/html
  mariadb:
    image: mariadb:latest
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb:/opt/data
      - ./docker/schema:/docker-entrypoint-initdb.d
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    environment:
      - TZ=Asia/Bangkok
      - MYSQL_ROOT_PASSWORD=toorp@ssw0rd
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8036:80"
    links:
      - "mariadb:mariadb"
    environment:
      PMA_HOST: "mariadb"
      PMA_PORT: 3306
  app:
    build: .
    volumes:
      - ./goapp:/app
      - "gocache:/go/pkg/mod/cache"
    working_dir: /app
    environment:
      - "GO111MODULE=on"
    command: "go mod download"
